### ISSUE TITLE
ERROR collectBrokerRuntimeStats-parse or report broker runtime stats error!

### ISSUE THREAD

**Issue by jamepika** [apache/rocketmq-exporter#117]
I got an error after started  the rocketmq-exporter and i could't  get any data in my grafana dashboard, can anyone help me? Thanks!

thread details are here:D

[2022-11-10 15:20:15.000]  INFO broker stats collection task starting....
[2022-11-10 15:20:15.000]  INFO consumer offset collection task starting....
[2022-11-10 15:20:15.000]  INFO producer metric collection task starting....
[2022-11-10 15:20:15.004]  INFO producer metric collection task ended....
[2022-11-10 15:20:15.004]  INFO broker topic stats collection task starting....
[2022-11-10 15:20:15.004] ERROR collectBrokerRuntimeStats-parse or report broker runtime stats error, {"table":{"msgPutTotalTodayNow":"0","commitLogDiskRatio_/root/store/commitlog":"0.14","commitLogDiskRatio":"0.14","getFoundTps":"0.0 0.06665888979619045 0.06665911196731036","EndTransactionThreadPoolQueueCapacity":"100000","sendThreadPoolQueueHeadWaitTimeMills":"0","putMessageDistributeTime":"[<=0ms]:0 [0~10ms]:0 [10~50ms]:0 [50~100ms]:0 [100~200ms]:0 [200~500ms]:0 [500ms~1s]:0 [1~2s]:0 [2~3s]:0 [3~4s]:0 [4~5s]:0 [5~10s]:0 [10s~]:0 ","queryThreadPoolQueueHeadWaitTimeMills":"0","remainHowManyDataToFlush":"0 B","msgGetTotalTodayNow":"132","putMessageFailedTimes":"0","putLatency999":"0.00","commitLogMaxOffset":"7658560","queryThreadPoolQueueSize":"0","getMessageEntireTimeMax":"19","msgPutTotalTodayMorning":"0","putMessageTimesTotal":"1","putLatency99":"0.00","bootTimestamp":"1668062829373","msgGetTotalTodayMorning":"0","msgPutTotalYesterdayMorning":"0","msgGetTotalYesterdayMorning":"0","pullThreadPoolQueueSize":"0","brokerVersionDesc":"V4_9_4","sendThreadPoolQueueSize":"0","startAcceptSendRequestTimeStamp":"0","commitLogMinOffset":"0","putMessageEntireTimeMax":"0","pullThreadPoolQueueHeadWaitTimeMills":"0","runtime":"[ 0 days, 0 hours, 33 minutes, 5 seconds ]","earliestMessageTimeStamp":"-1","commitLogDirCapacity":"Total : 47.0 GiB, Free : 40.5 GiB.","dispatchMaxBuffer":"0","brokerVersion":"401","putTps":"0.0 0.0 0.0","remainTransientStoreBufferNumbs":"2147483647","getMissTps":"0.19998000199980004 0.6332594530638092 0.7165854536485865","queryThreadPoolQueueCapacity":"20000","putMessageAverageSize":"0.0","getTransferedTps":"0.0 0.06665888979619045 0.06665911196731036","dispatchBehindBytes":"0","putMessageSizeTotal":"0","sendThreadPoolQueueCapacity":"10000","EndTransactionQueueSize":"0","getTotalTps":"0.19998000199980004 0.6999183428599995 0.7832445656158968","pullThreadPoolQueueCapacity":"100000","consumeQueueDiskRatio":"0.14","pageCacheLockTimeMills":"0"}}
java.lang.NullPointerException: null
        at org.apache.rocketmq.exporter.model.BrokerRuntimeStats.loadTps(BrokerRuntimeStats.java:149)
        at org.apache.rocketmq.exporter.model.BrokerRuntimeStats.<init>(BrokerRuntimeStats.java:94)
        at org.apache.rocketmq.exporter.task.MetricsCollectTask.collectBrokerRuntimeStats(MetricsCollectTask.java:683)
        at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
[2022-11-10 15:20:15.004]  INFO broker runtime stats collection task finished....4
[2022-11-10 15:20:15.009]  INFO broker stats collection task finished....9
[2022-11-10 15:20:15.070]  INFO topic offset collection task finished....70

**Comment by tadykid** [comment]
I had the same problem.guessing that after this 

I also encountered the same problem, guessing that the update [https://github.com/apache/rocketmq-exporter/pull/103](url) caused the plug-in incompatibility.

**Comment by haoqiya** [comment]
In the BrokerRuntimeStats  file, replace getTransferredTps with getTransferedTps ,then rebuild the project.
