### ISSUE TITLE
本地启动报空指针错误

### ISSUE THREAD

**Issue by zhoushuai1119** [apache/rocketmq-exporter#118]
1：rocketmq version：4.9.4
2：rocketmq 开启了权限认证
3：修改rocketmq-exporter本地配置文件
![image](https://user-images.githubusercontent.com/29701159/201267237-ddbbaf6d-0810-4a6c-bc04-7c24c7ac9837.png)

启动本地报空指针异常
`2022-11-11 12:59:15 【TID: N/A】 | [pool-2-thread-2] | INFO  | o.apache.rocketmq.exporter.task.MetricsCollectTask.collectTopicOffset:147 - topic offset collection task starting.... 
2022-11-11 12:59:15 【TID: N/A】 | [pool-2-thread-4] | ERROR | o.apache.rocketmq.exporter.task.MetricsCollectTask.collectBrokerRuntimeStats:688 - collectBrokerRuntimeStats-parse or report broker runtime stats error, {"table":{"msgPutTotalTodayNow":"14","commitLogDiskRatio_/root/store/commitlog":"0.25","commitLogDiskRatio":"0.25","getFoundTps":"0.0 0.0 0.0","EndTransactionThreadPoolQueueCapacity":"100000","sendThreadPoolQueueHeadWaitTimeMills":"0","putMessageDistributeTime":"[<=0ms]:0 [0~10ms]:0 [10~50ms]:0 [50~100ms]:0 [100~200ms]:0 [200~500ms]:0 [500ms~1s]:0 [1~2s]:0 [2~3s]:0 [3~4s]:0 [4~5s]:0 [5~10s]:0 [10s~]:0 ","queryThreadPoolQueueHeadWaitTimeMills":"0","remainHowManyDataToFlush":"0 B","msgGetTotalTodayNow":"61","putMessageFailedTimes":"0","putLatency999":"0.00","commitLogMaxOffset":"9705","queryThreadPoolQueueSize":"0","getMessageEntireTimeMax":"17","msgPutTotalTodayMorning":"14","putMessageTimesTotal":"14","putLatency99":"0.00","bootTimestamp":"1667457282291","msgGetTotalTodayMorning":"61","msgPutTotalYesterdayMorning":"12","msgGetTotalYesterdayMorning":"61","pullThreadPoolQueueSize":"0","brokerVersionDesc":"V4_9_4","sendThreadPoolQueueSize":"0","startAcceptSendRequestTimeStamp":"0","commitLogMinOffset":"0","putMessageEntireTimeMax":"27","pullThreadPoolQueueHeadWaitTimeMills":"0","runtime":"[ 7 days, 22 hours, 24 minutes, 32 seconds ]","earliestMessageTimeStamp":"-1","commitLogDirCapacity":"Total : 58.9 GiB, Free : 42.6 GiB.","dispatchMaxBuffer":"0","brokerVersion":"401","putTps":"0.0 0.0 0.0","remainTransientStoreBufferNumbs":"2147483647","getMissTps":"0.0 0.7999066775542854 0.5599328080630325","queryThreadPoolQueueCapacity":"20000","putMessageAverageSize":"693.2142857142857","getTransferedTps":"0.0 0.0 0.0","dispatchBehindBytes":"0","putMessageSizeTotal":"9705","sendThreadPoolQueueCapacity":"10000","EndTransactionQueueSize":"0","getTotalTps":"0.0 0.7999066775542854 0.5599328080630325","pullThreadPoolQueueCapacity":"100000","consumeQueueDiskRatio":"0.25","pageCacheLockTimeMills":"0"}} 
java.lang.NullPointerException: null
	at org.apache.rocketmq.exporter.model.BrokerRuntimeStats.loadTps(BrokerRuntimeStats.java:149)
	at org.apache.rocketmq.exporter.model.BrokerRuntimeStats.<init>(BrokerRuntimeStats.java:94)
	at org.apache.rocketmq.exporter.task.MetricsCollectTask.collectBrokerRuntimeStats(MetricsCollectTask.java:685)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by HelloWorDomain** [comment]
这个问题和我们同事遇到的报错一致。可以对这部分加1个判断，规避null带来的影响。
