### ISSUE TITLE
Grafana dashboard can't show most of the metrics

### ISSUE THREAD

**Issue by maixiaohai** [apache/rocketmq-exporter#29]
**Describe the bug**
Grafana dashboard can't show most of the metrics

![image](https://user-images.githubusercontent.com/3734319/88765443-1201af80-d1a9-11ea-89fa-e695badd7af0.png)

```
exporter version: 0.0.2-SNAPSHOT
rocketmq version: 4.7.0
prometheus version: 2.20.0
grafana version: 6.2.5
dashboard config : rocketmq-dashboard_rev3.json
```

**Additional context**
Exporter log many error like this:
```WARN addGroupGetLatencyByStoreTimeMetric error
java.lang.NullPointerException: null
	at org.apache.rocketmq.exporter.task.MetricsCollectTask.collectConsumerOffset(MetricsCollectTask.java:345)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by maixiaohai** [comment]
Hi I have found the solution, the query datasource is 'deafult'.
But why the dashborad panel use different datasource? Kind of strange
![image](https://user-images.githubusercontent.com/3734319/88787632-bf36f080-d1c6-11ea-839f-bfc2c8093669.png)
