### ISSUE TITLE
lots of rocketmq_group_diff metrics data loss

### ISSUE THREAD

**Issue by maixiaohai** [apache/rocketmq-exporter#53]
**Describe the bug**
Ｗe have lots of rocketmq_group_diff metrics data loss, exporter log some exception as follows:
```
java.lang.NullPointerException: null
        at org.apache.rocketmq.exporter.task.MetricsCollectTask.collectConsumerOffset(MetricsCollectTask.java:320)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
**When the npe throw, the whole collect task will stop which cause lots of data loss.**

**Additional context**
We have some pyhon sdk which can't get messageModel, the npe throw from here.
![image](https://user-images.githubusercontent.com/3734319/114023851-f73e1980-98a5-11eb-9ac8-c9396999db93.png)

**Comment by maixiaohai** [comment]
After fix, the metrics data recover
![image](https://user-images.githubusercontent.com/3734319/114024733-fce82f00-98a6-11eb-8c14-7ed162780940.png)
