### ISSUE TITLE
Whether to support rocketmq 4.9 DLedger  cluster?

### ISSUE THREAD

**Issue by fsckzy** [apache/rocketmq-exporter#61]
cluster info:
![image](https://user-images.githubusercontent.com/34021474/127289505-cfef6e72-374a-4595-a49b-ca652cb6c682.png)

step:
```shell
git clone https://github.com.cnpmjs.org/apache/rocketmq-exporter.git
mvn clean install                                                   
nohup java -jar rocketmq-exporter-0.0.2-SNAPSHOT.jar --rocketmq.config.namesrvAddr=10.16.100.60:9876 -rocketmq.config.rocketmqVersion=V4.9.0 &
#or
nohup java -jar rocketmq-exporter-0.0.2-SNAPSHOT.jar --rocketmq.config.namesrvAddr=10.16.100.60:9876 -rocketmq.config.rocketmqVersion=V4_9_0 &
```

error:
```shell
[2021-07-28 16:13:32.952]  INFO Starting RocketMQExporterApplication v0.0.2-SNAPSHOT on mq2 with PID 4082 (/data/prometheus/rocketmq-exporter/rocketmq-exporter-0.0.2-SNAPSHOT.jar started by root in /data/prometheus/rocketmq-exporter)
[2021-07-28 16:13:32.955]  INFO No active profile set, falling back to default profiles: default
[2021-07-28 16:13:33.974]  INFO Tomcat initialized with port(s): 5557 (http)
[2021-07-28 16:13:33.991]  INFO Initializing ProtocolHandler ["http-nio-5557"]
[2021-07-28 16:13:34.002]  INFO Starting service [Tomcat]
[2021-07-28 16:13:34.002]  INFO Starting Servlet engine: [Apache Tomcat/9.0.14]
[2021-07-28 16:13:34.014]  INFO The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
[2021-07-28 16:13:34.087]  INFO Initializing Spring embedded WebApplicationContext
[2021-07-28 16:13:34.088]  INFO Root WebApplicationContext: initialization completed in 1092 ms
[2021-07-28 16:13:34.185]  INFO setNameSrvAddrByProperty nameSrvAddr=10.16.100.60:9876
[2021-07-28 16:13:34.190]  INFO setWebTelemetryPath webTelemetryPath=/metrics
[2021-07-28 16:13:34.191]  INFO setRocketmqVersion rocketmqVersion=490
RocketMQLog:WARN No appenders could be found for logger (io.netty.util.internal.PlatformDependent0).
RocketMQLog:WARN Please initialize the logger system properly.
[2021-07-28 16:14:02.518]  INFO MetricsCollectTask init starting....
[2021-07-28 16:14:05.519]  WARN Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metricsCollectTask': Invocation of init method failed; nested exception is org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to null failed
[2021-07-28 16:14:05.529]  INFO Stopping service [Tomcat]
[2021-07-28 16:14:05.539]  INFO 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[2021-07-28 16:14:05.542] ERROR Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metricsCollectTask': Invocation of init method failed; nested exception is org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to null failed
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1737)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at org.apache.rocketmq.exporter.RocketMQExporterApplication.main(RocketMQExporterApplication.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to null failed
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:394)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getBrokerClusterInfo(MQClientAPIImpl.java:1333)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineBrokerClusterInfo(DefaultMQAdminExtImpl.java:306)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.examineBrokerClusterInfo(DefaultMQAdminExt.java:251)
	at org.apache.rocketmq.exporter.service.client.MQAdminExtImpl.examineBrokerClusterInfo(MQAdminExtImpl.java:227)
	at org.apache.rocketmq.exporter.task.MetricsCollectTask.init(MetricsCollectTask.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 26 common frames omitted
```

what do I do?

**Comment by francisoliverlee** [comment]
someone already tried, ref this issue
https://github.com/apache/rocketmq-exporter/issues/62
