### ISSUE TITLE
BROKER_PUT_NUMS not exist

### ISSUE THREAD

**Issue by lygn128** [apache/rocketmq-exporter#88]
**Describe the bug**
[2022-01-05 16:42:15.039] ERROR BROKER_PUT_NUMS-error, master broker=xxxxxxx:1011
org.apache.rocketmq.client.exception.MQClientException: CODE: 1  DESC: The stats <BROKER_PUT_NUMS> <rocketmq-xxxxxxxxxx> not exist
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.viewBrokerStatsData(MQClientAPIImpl.java:2065)
        at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.viewBrokerStatsData(DefaultMQAdminExtImpl.java:908)
        at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.viewBrokerStatsData(DefaultMQAdminExt.java:455)
        at org.apache.rocketmq.exporter.service.client.MQAdminExtImpl.viewBrokerStatsData(MQAdminExtImpl.java:502)
        at org.apache.rocketmq.exporter.task.MetricsCollectTask.collectBrokerStats(MetricsCollectTask.java:560)
        at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hdchen** [comment]
This is just a warning ，and  does not affect monitoring metrics,
when The producer does not produce messages,this warning will appear. BROKER_PUT_NUMS,TOPIC_PUT_SIZE
